export const PERMISSIONS = {
  "users:read": { category: "users" },
  "users:write": { category: "users" },
  "users:delete": { category: "users" },
  "departments:read": { category: "departments" },
  "departments:write": { category: "departments" },
  "departments:delete": { category: "departments" },
  "roles:read": { category: "roles" },
  "roles:write": { category: "roles" },
  "roles:delete": { category: "roles" },
  "memberships:read": { category: "memberships" },
  "memberships:write_global": { category: "memberships" },
  "memberships:write_dept": { category: "memberships" },
  "memberships:delete": { category: "memberships" },
  "photos:read": { category: "photos" },
  "photos:write_global": { category: "photos" },
  "photos:write_dept": { category: "photos" },
  "shop:read": { category: "shop" },
  "shop:write": { category: "shop" },
  "orders:read": { category: "orders" },
  "orders:read_customer": { category: "orders" },
  "orders:create": { category: "orders" },
  "orders:write": { category: "orders" },
  "orders:delete": { category: "orders" },
  "orders:override": { category: "orders" },
  "voting:read": { category: "voting" },
  "voting:write": { category: "voting" },
} as const;

export type Permission = keyof typeof PERMISSIONS;
