name: Deploy Production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag or branch to deploy'
        required: true
        default: 'main'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://neiist.tecnico.ulisboa.pt

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Upload Deployment Script
        run: |
          scp -o StrictHostKeyChecking=no scripts/deploy_prod.sh \
              ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/neiist/deploy_prod.sh
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
              "chmod +x /home/neiist/deploy_prod.sh"

      - name: Determine Deploy Ref
        id: deploy_ref
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "REF=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "REF=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
           "su - neiist -c 'bash ~/deploy_prod.sh ${{ env.REF }}'"

      - name: Confirm Production Deployment
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
          "su - neiist -c 'bash -lc \"pm2 jlist\"'" | jq -r '.[] | select(.name=="blue" or .name=="green") | "🌿 " + .name + " → " + .pm2_env.status'
