name: Deploy Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag or branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.neiist.rnl.tecnico.ulisboa.pt

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Upload Deployment Script
        run: |
          scp -o StrictHostKeyChecking=no scripts/deploy_staging.sh \
              ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/neiist/deploy_staging.sh
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
              "chmod +x /home/neiist/deploy_staging.sh"

      - name: Determine Deploy Ref
        id: deploy_ref
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "REF=main" >> $GITHUB_ENV
          else
            echo "REF=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Staging
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
          "su - neiist -c 'bash ~/deploy_staging.sh ${{ env.REF }}'"

      - name: Confirm Staging Deployment
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
          "su - neiist -c 'bash -lc \"pm2 jlist\"'" | jq -r '.[] | select(.name=="neiist_server_staging" or .name=="staging") | "🌿 " + .name + " → " + .pm2_env.status'
